server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docops
    username: docops
    password: docops

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: workflow
        

  flyway:
    enabled: true
    schemas: workflow
    table: workflow_flyway_history
    validate-on-migrate: true
    baseline-on-migrate: false
    
#  workflow:
 # base-url: http://localhost:${server.port}  
  
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: workflow-service