server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docops
    username: docops
    password: docops

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false   # first time only true after 1st run make it false


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.flywaydb: INFO
    


jwt:
  secret: docops-secret-key-very-long-at-least-32-characters
  
storage:
  base-dir: E:/Workspace_11012025_AI_Doc/storage/
