global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: "workflow-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "worker-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8090"]